### ISSUE TITLE
Same error message

### ISSUE THREAD

**Issue by birrataha** [billgreenwald/Pubmed-Batch-Download#11]
I'm getting the same error regardless of what I do.

` python fetch_pdfs.py -pmf example_pmf.tsv` 
Trying to fetch pmid 28514316
** Reprint 28514316 cannot be fetched as ovid is not supported by the requests package.
` python fetch_pdfs.py -pmid 30374447` 
Trying to fetch pmid 28514316
** Reprint 28514316 cannot be fetched as ovid is not supported by the requests package.

the pubmed ID it is even requesting is incorrect....

**Comment by birrataha** [comment]
In the latest update, 6 or 7 lines were uncommented out that set the args reference to some sample PubmedID (28514316). After re-commenting those lines, it fixed it.

**Comment by billgreenwald** [comment]
Sorry about that, pushed a version that had those commented out now.

Thanks!
