### ISSUE TITLE
Trouble with Elsevier articles

### ISSUE THREAD

**Issue by OgnjenMilicevic** [billgreenwald/Pubmed-Batch-Download#14]
Hello!

I am having trouble downloading Elsevier papers, even though I can access them through my academic network. Here are the PMIDs:

30898248
29934065
28325353
28256256

I have many more. Any help you can give is greatly appreciated!

**Comment by billgreenwald** [comment]
Edited:  The backend to the pubmed api seems to be blocking requests, which breaks everything -- I'll investigate and try to fix when I can

**Comment by billgreenwald** [comment]
Ok I fixed it but had to migrate to python3 in order to get it to work.  I need to update the yml, readme instructions, and then push everything, but you should be able to expect an update sometime tomorrow that resolves this issue.

**Comment by OgnjenMilicevic** [comment]
Your responsiveness and efficiency are just amazing! Thank you!

**Comment by billgreenwald** [comment]
the new version is live -- let me know if it works.  You will need to install the new version of python, but I updated the .yml so you can use it to make a new conda environment easily.  Let me know if it works or if you have other questions.

**Comment by OgnjenMilicevic** [comment]
Hi, thanks for the update, but unfortunately it doesn't work for me. I am not sure if I can help you debug this further in any way?
To specify, I have automatic access to Elsevier papers via my institution, and I can access them from the browser. The link for me for paper "30898248" is "https://www.sciencedirect.com/science/article/pii/S1936879818321319/pdfft?md5=5bd79a6cab6a0a842fe595eab73d8b8c&pid=1-s2.0-S1936879818321319-main.pdf".

Also, when I take this link and put it in a different browser, it asks me to select my institution:
"https://www.sciencedirect.com/user/chooseorg?targetURL=%2Fscience%2Farticle%2Fpii%2FS1936879818321319%2Fpdfft"

<img width="1206" alt="Screen Shot 2019-06-14 at 2 38 22 PM" src="https://user-images.githubusercontent.com/16489606/59509777-4685af80-8eb2-11e9-8a90-1da833378295.png">


Could this be preventing the automated download? I only agree to it once per browser session, and afterwards I have no problem reading the pdfs in it.

**Comment by billgreenwald** [comment]
My university has access but we don't need to select our organization -- this is probably messing you up yes.  What browser can you access them through without needing to select institution, and what browser do you need to select it in?

Also to help, can you try going via a browser to the site using the NCBI api?  Use the URL

```
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=pubmed&id={0}&retmode=ref&cmd=prlinks
```

but sub in the pmid where it says {0}

**Comment by billgreenwald** [comment]
I am closing this unless I hear something new
