### ISSUE TITLE
fetching error

### ISSUE THREAD

**Issue by ZsoltTuri** [billgreenwald/Pubmed-Batch-Download#16]
I got the same error for all PMIDs I tried so far. 
Eg, ** fetching of reprint 123 failed from error list index out of range
I use version pubmed-batch-download 3.0.0, python 3.7.4.

**Comment by billgreenwald** [comment]
Could you please provide some actual pmids to try. Thanks!

**Comment by ZsoltTuri** [comment]
Logging out and in to the server solved the problem. 
As of note, I tried many different PMIDs from Science Direct, Plos, etc. and received the same error (error list index out of range). Now it seems to work. Sorry to prematurely initiating this issue!

**Comment by billgreenwald** [comment]
No worries!
