### ISSUE TITLE
Change require to require_relative

### ISSUE THREAD

**Issue by dbujold** [billgreenwald/Pubmed-Batch-Download#3]
To enable using the script from another directory, it'd be good to change 
require './pdfetch.rb'
to
require_relative './pdfetch.rb'

Thank you,

David

**Comment by billgreenwald** [comment]
Good suggestion--done.

**Comment by billgreenwald** [comment]
Marking as closed as I have not heard more in a month.

**Comment by dbujold** [comment]
It worked, thanks for the change! :-)

**Comment by billgreenwald** [comment]
Glad to hear it.  I am currently trying to sort out a bug for some other users, but am having difficulty nailing down the culprit.  Out of curiosity, if you are able to download articles with the program, would be able to tell me:

Your ruby version
Your mechanize version
Your camping version
Your socksify version
A pmid of an article that you were able to fetch?

Thanks!

**Comment by dbujold** [comment]
There you go:

Your ruby version: 2.2.7p470
Your mechanize version: 2.7.5
Your camping version: 2.1.532
Your socksify version: 1.7.1
A pmid of an article that you were able to fetch: 27160855
