### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by dmcalli2** [billgreenwald/Pubmed-Batch-Download#7]
Hello,
I am getting an index out of range error for certain PMIDs.
I am able to download about 1 in 3 PMIDs I am seeking and the most common error is "index out of range"
Could the loop indexing be longer than the list of possible errors?
Many thanks

**Comment by billgreenwald** [comment]
Could you paste the full error you are receiving, and the command you run?

**Comment by dmcalli2** [comment]
Thanks for the quick reply!
Some of the error has gone of the top of my terminal, so I cant paste the full list.
However, here is an example of the output for a successful and unsuccessful PMID.
** fetching reprint using the 'generic citation labelled' finder...
** fetching of reprint 24481874 succeeded
Trying to fetch pmid 25282519
Trying genericCitationLabelled
Trying pubmed_central
Trying acsPublications
Trying uchicagoPress
** fetching of reprint 25282519 failed from error list index out of range

The command was:-
python2.7 fetch_pdfs.py -pmf mypmf.txt

I am running Python 2.7 in Ubuntu from within Windows Subsystem for Linux (WSL).

**Comment by billgreenwald** [comment]
I had a typo from some debugging left, it would seem.  I believe i fixed it, and 25282519 downloaded fine as a test.  Let me know if the new version works.

**Comment by dmcalli2** [comment]
Works perfectly.
Thanks very much, and thanks for sharing your code.

**Comment by nmehra222** [comment]
Hi Bill,
Thanks so much for making this tool. I am also having the index out of range error. I am able to download about 7 of the 50 papers I am intending to, with roughly half of the papers receiving this error. Here's an example of the error message I'm getting:
Trying to fetch pmid 29930241
Trying genericCitationLabelled
Trying pubmed_central_v1
Trying acsPublications
Trying uchicagoPress
Trying nejm
Trying futureMedicine
Trying science_direct
** fetching of reprint 29930241 failed from error list index out of range

I am working with a pmf and am not sure where the error is coming from.
Thanks!

**Comment by billgreenwald** [comment]
Hey @nmehra222, sorry for the slow response.  I tried to get your example PMID and got a "bad handshake" error from the site instead; it could be because I am out of the country and thus have some, though I don't think that is why.  Can you post or send a link to your pmf file so that I can try using it for error checking?  Thanks!

**Comment by nmehra222** [comment]
I actually tried again, and was able to download the paper without a problem. Thanks for your help!
